name: ccleste-nx-build

on:
  push:
  workflow_dispatch:
  pull_request:

permissions:
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    steps:
    - uses: actions/checkout@v1
  
    - name: build ccleste
      run: | 
        make
